---

system_packages:
  - varnish
  - nginx
  - openssl

# recommended to be same (or double) the number of processors
nginx_worker_processes: 16

# default is 1024
nginx_worker_connections: 4096

# default is 65
nginx_keepalive_timeout: 65

# this is the certificate name to be used in the Nginx config
nginx_ssl_certificate_name_to_use: multi_domain_june_2014

# this is the certificate to generate a key and csr for
nginx_ssl_certificate_name_to_install: multi_domain_june_2014

ssl_certificate_domains:
  - learningequality.org
  - kalite.learningequality.org
  - kalite.adhocsync.com
  - forums.learningequality.org
  - hub.learningequality.org

primary_ssl_certificate_domain: learningequality.org


ufw_enabled: yes

ufw_allowed_ports:
  - 80
  - 443
  - 7007
  - 8008


proxy_backends:

  - name: kitchen_downloads
    host: kitchen
    port: 80

  - name: citadel_fle_home
    host: citadel
    port: "{{ citadel_flehome_port }}"

  - name: keep_ka_lite_central
    host: keep
    port: "{{ keep_ka_lite_central_port }}"

  - name: globe_fle_home
    host: globe
    port: "{{ citadel_flehome_port }}"

  - name: globe_ka_lite_central
    host: globe
    port: "{{ keep_ka_lite_central_port }}"

  - name: scriptorium_forums
    host: scriptorium
    port: 80

  - name: old_adhocsync_dev_server
    host: 174.129.228.112
    port: 7007

  - name: field_kalite_demo
    host: 162.242.161.163
    port: 8008

# this location will be added to any vhost in virtual_hosts that doesn't define a "locations" list
default_location:
  - path: /

virtual_hosts:

  - hosts:
      - learningequality.org
    backend: citadel_fle_home
    force_https: yes
    locations:
      - path: /
        varnish: yes
      - path: /downloads
        backend: kitchen_downloads
    allow_https: yes

  - hosts:
      - hub.learningequality.org
    backend: keep_ka_lite_central
    allow_https: yes
    locations:
      - path: /
        force_https: yes
      - path: ~ ^/(accounts|wiki|contact|securesync|admin)
        force_https: yes
      - path: ~ ^/(content|static|media)
        varnish: yes

  - hosts:
      - flestaging.learningequality.org
    backend: globe_fle_home
    locations:
      - path: /

  - hosts:
      - staging.learningequality.org
      - adhoc.learningequality.org
    ports: ["80", "7007"]
    backend: globe_ka_lite_central
    locations:
      - path: /
      - path: ~ ^/($|faq)
        varnish: yes
      - path: ~ ^/(accounts|wiki|contact|securesync|admin)
      - path: ~ ^/(content|static|media)
        varnish: yes

  - hosts:
      - kalite.adhocsync.com
      - adhocsync.com
      - kalite.learningequality.org
    locations:
      - path: = /
        redirect: https://learningequality.org/ka-lite/
      - path: /
        backend: keep_ka_lite_central
    allow_https: yes

  - hosts:
      - forums.learningequality.org
    backend: scriptorium_forums
    force_https: yes
    allow_https: yes

  - hosts:
      - kalite.learningequality.org
      - kalite.adhocsync.com
      - hub.learningequality.org
    ports: ["7007", "8008 ssl"]
    locations:
      - path: /
        redirect: https://hub.learningequality.org/
    allow_https: yes

  - hosts:
      - demo.learningequality.org
    backend: field_kalite_demo

  - ports:
      - "80 default"
    locations:
      - path: /
        redirect: https://learningequality.org/