---
    
- name: add the nodejs ppa
  shell: curl -sL https://deb.nodesource.com/setup | sudo bash -
  sudo: yes
  tags:
    - setupnodejs

- name: install nodejs
  apt: name=nodejs
  sudo: yes
  tags:
    - setupnodejs

- name: Create the /var/www directory and set it as belonging to the www-data user.
  file: dest=/var/www owner=www-data state=directory
  sudo: yes

- name: Clone the ka-lite git repository and checkout the desired branch.
  git: repo=https://github.com/learningequality/ka-lite.git version={{ ka_lite_distributed_git_branch }} dest=/var/www/{{ ka_lite_distributed_prefix }} update=true
  sudo: yes
  sudo_user: www-data
  register: ka_lite_distributed_clone

- name: Put the custom settings file into the KA Lite data directory.
  template: src=custom_settings.py.j2 dest=/var/www/.kalite/settings.py
  sudo: yes
  sudo_user: www-data

- name: install requirements
  pip: requirements=/var/www/{{ ka_lite_distributed_prefix }}/requirements_dev.txt
  sudo: yes
  ignore_errors: yes

- name: Run setup command to ensure KA Lite is initialized (new install or upgrade).
  shell: "echo 'yes\n' | /var/www/{{ ka_lite_distributed_prefix }}/bin/kalite manage setup --noinput -u{{ ka_lite_distributed_django_superuser_name }} -e{{ ka_lite_distributed_django_superuser_email }} -p{{ ka_lite_distributed_django_superuser_pass }}"
  register: setup
  sudo: yes
  sudo_user: www-data
  when: ka_lite_distributed_django_superuser_name is defined and ka_lite_distributed_django_superuser_email is defined and ka_lite_distributed_django_superuser_pass is defined
  changed_when: "'Migrating forwards' in setup.stdout"
  tags:
    - setupkalite
  # failed_when: "setup.stderr"

- name: download nodejs deps
  shell: npm install
  args:
    chdir: /var/www/{{ ka_lite_distributed_prefix }}/
  sudo: yes
  sudo_user: www-data
  register: setup
  tags:
    - setupassets

- name: Build static files
  shell: node build.js --staticfiles
  args:
    chdir: /var/www/{{ ka_lite_distributed_prefix }}/
  sudo: yes
  sudo_user: www-data
  register: setup
  tags:
    - setupassets

- name: Run setup command to ensure KA Lite is initialized (upgrade).
  shell: "echo 'yes\n' | /var/www/{{ ka_lite_distributed_prefix }}/bin/kalite manage setup --noinput"
  register: setup
  sudo: yes
  sudo_user: www-data
  when: ka_lite_distributed_django_superuser_name is not defined or ka_lite_distributed_django_superuser_email is not defined or ka_lite_distributed_django_superuser_pass is not defined
  changed_when: "'Migrating forwards' in setup.stdout"
  # failed_when: "setup.stderr"

- name: Create cron job to start the demo server at boot.
  cron: 'name="run {{ ka_lite_distributed_prefix }} distributed server" special_time=reboot job="/var/www/{{ ka_lite_distributed_prefix }}/start.sh" user=www-data'
  sudo: yes
  sudo_user: www-data

- name: Create cron job to delete the videos in the content directory frequently if desired.
  cron: 'name="delete {{ ka_lite_distributed_prefix }} content" minute="0,20,40" job="rm /var/www/{{ ka_lite_distributed_prefix }}/content/*.*" user=www-data'
  sudo: yes
  when: ka_lite_distributed_delete_content_frequently is defined and ka_lite_distributed_delete_content_frequently
  sudo_user: www-data

- name: Run/restart the distributed server.
  shell: "/var/www/{{ ka_lite_distributed_prefix }}/bin/kalite restart --settings={{ ka_lite_distributed_settings_module }} --port={{ ka_lite_distributed_port }}"
  sudo: yes
  sudo_user: www-data
  tags:
    - startkalite
  # when: ka_lite_distributed_clone.changed